version: "3.8"
services:
  server:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SERVER_B_HOST=http://server-b:8085
      - HOSTNAME=localhost:8080
      - PORT=8080
      - ZIPKIN_URL=http://zipkin:9411/api/v2/spans
    command: ["/root/server"]
    depends_on:
      - server-b
      - zipkin

  server-b:
    build: .
    ports:
      - "8085:8085"
    environment:
      - WEATHER_API_KEY=d365dc42c04f4ad9805201403250403
      - HOSTNAME=localhost:8085
      - PORT=8085
      - ZIPKIN_URL=http://zipkin:9411/api/v2/spans
    command: ["/root/server-b"]

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
