basePath: /
definitions:
  handlers.WeatherRequest:
    properties:
      cep:
        type: string
    type: object
  handlers.WeatherResponse:
    properties:
      temp_C:
        type: number
      temp_F:
        type: number
      temp_K:
        type: number
    type: object
info:
  contact: {}
  description: API que recebe um CEP e retorna a temperatura atual.
  title: Clima API
  version: "1.0"
paths:
  /weather:
    post:
      consumes:
      - application/json
      description: Retorna a temperatura em Celsius, Fahrenheit e Kelvin
      parameters:
      - description: CEP para consulta
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.WeatherRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.WeatherResponse'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "422":
          description: Unprocessable Entity
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Obtém a temperatura de uma cidade a partir do CEP
      tags:
      - Clima
swagger: "2.0"
