basePath: /
definitions:
  services.WeatherResponse:
    properties:
      temp_C:
        type: number
      temp_F:
        type: number
      temp_K:
        type: number
    type: object
info:
  contact: {}
  description: API que recebe um CEP e retorna o nome da cidade equivalente ao CEP.
  title: Cidade API
  version: "1.0"
paths:
  /get-temperature-by-zipcode:
    get:
      consumes:
      - application/json
      description: Retorna os graus de temperatura em Celsius, Fahrenheit e Kelvin
      parameters:
      - description: CEP para consulta
        in: query
        name: zipcode
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/services.WeatherResponse'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "422":
          description: Unprocessable Entity
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Obtém as temperaturas de uma cidade a partir do CEP
      tags:
      - Temperature
swagger: "2.0"
